### ISSUE TITLE
Outdated docs for time zones

### ISSUE THREAD

**Issue by mj1856** [python-babel/babel#108] opened 2014-08-31 22:56 UTC
The docs [here](http://babel.pocoo.org/docs/dates/) show the sample:

```python
>>> from babel import Locale
>>> from babel.dates import get_timezone_name, get_timezone

>>> tz = get_timezone('Europe/Berlin')
>>> get_timezone_name(tz, locale=Locale.parse('pt_PT'))
u'Hor\xe1rio Alemanha'
```
But the current code returns `"hora da Europa Central"`.  I assume that's because you're now resolving the time zone to the metazone and giving the translation for the metazone name.  That's fine, but the docs need to be updated.  Thanks.

**Comment by sils1297** [comment] 2015-09-21 15:55
Hi, @mj1856 we're currently short of manpower, just taking over this repository. We would love a PR for this. Apart from that I'm marking this as `easy` and `ready to work upon`,  thanks for submitting the bug!

**Comment by etanol** [comment] 2015-09-21 16:33
If you are using `master` it is probably caused by the update from CLDR 23.1 to CLDR 26

**Closed** 2015-10-06 16:35 UTC
Labels: (1) investigated, documentation, easy
