### ISSUE TITLE
backwards incompatibility with CLDR files?

### ISSUE THREAD

**Issue by Pikkupomo** [python-babel/babel#583] opened 2018-05-28 19:50 UTC
It seems something has leaked to the 2.6. which is not backwards compatible. 

Our tests here fail with 2.6.0 but pass with 2.5.3

The failing test:
https://github.com/shuup/shuup/blob/master/shuup_tests/core/test_units.py#L205

```
>           assert gram.render_quantity(qty) == '4 321 123,4567g'
E           assert '4\xa0321\xa0123,4567g' == '4 321 123,4567g'
E             - 4 321 123,4567g
E             ?  ^   ^
E             + 4 321 123,4567g
E             ?  ^   ^
```

This further calls https://github.com/shuup/shuup/blob/master/shuup/core/models/_units.py#L314 which finally calls our very on `format_number`here: https://github.com/shuup/shuup/blob/master/shuup/utils/i18n.py#L61

in this `format_number` the format is being fetched from the current locale, and this is where we run into problems. 

```python
def format_number(value, digits=None):
    locale = get_current_babel_locale()
    if digits is None:
        return format_decimal(value, locale=locale)
    (min_digits, max_digits) = (
        digits if isinstance(digits, tuple) else (digits, digits))
    format = locale.decimal_formats.get(None)
    pattern = parse_pattern(format)  # type: babel.numbers.NumberPattern
    return pattern.apply(value, locale, force_frac=(min_digits, max_digits))
```

With 2.5.3 you get the following patterns:
```
<NumberPattern '#0.######'>
<NumberPattern '#,##0.###'>
<NumberPattern '#,##0.###'>
<NumberPattern '#,##0.###'>
<NumberPattern '#,##,##0.###'>
<NumberPattern '#0.###'>
```

And, with 2.6, you get the following patterns:
```
<NumberPattern '0.######'>
<NumberPattern '#,##0.###'>
<NumberPattern '#,##0.###'>
<NumberPattern '#,##0.###'>
<NumberPattern '#,##,##0.###'>
<NumberPattern '#,##0.###'>
```

All this can be traced back to a change in `hy.dat` which has its pattern updated.

I guess it has something to do with the version changes of the used files (CLDR). 
https://github.com/python-babel/babel/blob/master/scripts/download_import_cldr.py#L16

Or, the issue is somewhere else and I just missed it (entirely possible) :)

Good job keeping this up to date 👍

**Comment by akx** [comment] 2018-06-18 13:58
Closing since this is expected behavior.

**Closed by akx** 2018-06-18 13:58 UTC
