### ISSUE TITLE
2.8.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [python-babel/babel#750] opened 2020-11-07 19:17 UTC
```
+ TZ=America/New_York
+ /usr/bin/python3 -m pytest
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.3, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/tkloczko/rpmbuild/BUILD/Babel-2.8.0/.hypothesis/examples')
rootdir: /home/tkloczko/rpmbuild/BUILD/Babel-2.8.0, configfile: setup.cfg
plugins: hypothesis-4.23.8, flaky-3.6.1, forked-1.3.0, xdist-2.1.0, shutil-1.7.0, virtualenv-1.7.0, cov-2.10.1
collected 0 items / 1 error

================================================================================== ERRORS ==================================================================================
______________________________________________________________________ ERROR collecting test session _______________________________________________________________________
Direct construction of DoctestModule has been deprecated, please use DoctestModule.from_parent.
See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.
========================================================================= short test summary info ==========================================================================
ERROR
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 1 error in 0.13s =============================================================================
```

**Comment by eli-schwartz** [comment] 2020-11-10 01:25
Duplicate of #747

**Comment by akx** [comment] 2020-11-11 08:36
Fixed by #752. Would a 2.8.1 patch release help?

**Closed** 2020-11-11 08:36 UTC

**Comment by kloczek** [comment] 2020-11-12 15:37
> Fixed by #752. Would a 2.8.1 patch release help?

Yes please :)

**Comment by akx** [comment] 2020-11-12 15:38
@kloczek 2.8.1 has a bugfix for this (discussed in #747), and 2.9.0 is also out with a fix.

Do note that tests currently require `TZ=UTC`; see #757 :)

**Comment by kloczek** [comment] 2020-11-12 22:38
Thx.

Just tested and all looks good.
PS. in Fedora is small patch against python 3.9 https://src.fedoraproject.org/rpms/babel/raw/master/f/babel-python39a6-compat.patch
