### ISSUE TITLE
Message extraction extracts map keys

### ISSUE THREAD

**Issue by remko** [python-babel/babel#400] opened 2016-04-28 14:50 UTC
Extracting strings from the following piece of code

    gettext(a["b"])

will extract `"b"` as a translatable string, whereas I wasn't expecting anything to be extracted.

**Comment by akx** [comment] 2016-07-15 13:34
Closing as a duplicate of #415 (as that has more discussion and examples). Thanks!

**Closed by akx** 2016-07-15 13:34 UTC
