### ISSUE TITLE
Date format seems wrong for es_AR

### ISSUE THREAD

**Issue by hobarrera** [python-babel/babel#149] opened 2015-03-15 13:12 UTC
>>> format_date(datetime.now(), locale="es_AR", format="short")
    u'15/03/15'

Unlike abroad, the two-digit year format completely dissapeared in 1999. I've never, *ever* seen anyone use two digits for a year after the nineties. (I *have* heard the oral expresion `'99`, but only spoken).

This is just plain confusing to most Argentine people (I myself am was born and currently live in Argentina), and merely seeing this makes us assume it's a foreign format ("is it yymmdd? or ddmmyyy?").

**Comment by remyroy** [comment] 2015-04-02 02:11
Babel uses data from the CLDR which is part of the Unicode body to format dates. It is the CLDR which provides format patterns which are then used to format dates using specific locales.

I downloaded the latest [CLDR release](http://cldr.unicode.org/index/downloads) (27.0.1) and checked the 'short' pattern for dates. Since the es_AR locale does not provide a specific version, it falls back on the more generic es locale. The pattern is 'd/M/yy' for the es locale which is consistent with the year showing only 2 digits.

CLDR could be wrong but I doubt it. If you truly believe that the 'short' pattern for es_AR should use 4 digits for the year, I would invite you to join the Unicode body and persuade them that this is the case and that it should be included in their next release of the CLDR data.

My suggestion would be to use a custom format that would show the 4 digits or try the 'medium' or 'long' format if you really need years to show using 4 digits.

This is not a bug and can be closed.

**Comment by patch** [comment] 2015-04-02 03:12
@hobarrera, you can file a ticket for the Unicode CLDR here: http://cldr.unicode.org/index/bug-reports

The locale data is continuously improved as bugs are reported (and many exist in such a large and complex data repository), new locales are added, new data types are supported, and the ways that people communicate within a country and/or language evolve over time. If you file a ticket, you have the highest chance of being affective if you provide references using the format that you propose. For example, links to websites of companies based in Argentina or scans/photos of publications from Argentina. Note though that the CLDR has a [semi-annual release process](http://cldr.unicode.org/index#TOC-General-Schedule-) and the next release is in mid-September, plus it takes additional time for projects like Babel to upgrade versions.

**Comment by etanol** [comment] 2015-09-28 23:05
Indeed, this is a CLDR bug, closing

**Closed by etanol** 2015-09-28 23:05 UTC
Labels: invalid
