### ISSUE TITLE
`pybabel extract` not working with constant inner f-strings

### ISSUE THREAD

**Issue by l1onsun** [python-babel/babel#1060] opened 2024-01-24 11:44 UTC
## Steps to Reproduce
```python
# main.py
f"some string to {_('translate')}"
```
```bash
pybabel extract -o locales/messages.pot
```
(pybabel 2.14.0)

## Actual Results
No strings extracted

## Expected Results
extracted `'translate'` string

**Comment by tomasr8** [comment] 2024-09-04 17:53
Looks like a duplicate of #1001 
Also, this works as expected in the latest babel version

**Closed** 2024-10-08 13:40 UTC
