### ISSUE TITLE
test_get_timezone_name fails in fixed-offset timezones

### ISSUE THREAD

**Issue by jwilk** [python-babel/babel#441] opened 2016-08-20 19:09 UTC
# Overview Description

`test_get_timezone_name` seems to fail in fixed-offset timezones, such as `Etc/GMT-7`.
# Steps to Reproduce

```
$ TZ=Etc/GMT-7 python -m pytest tests/test_dates.py 
======================================= test session starts ========================================
platform linux2 -- Python 2.7.9, pytest-3.0.0, py-1.4.31, pluggy-0.3.1
rootdir: /home/jwilk/babel, inifile: setup.cfg
collected 68 items 

tests/test_dates.py .......................................................F............

============================================= FAILURES =============================================
______________________________________ test_get_timezone_name ______________________________________

    def test_get_timezone_name():
        dt = time(15, 30, tzinfo=timezone('America/Los_Angeles'))
        assert (dates.get_timezone_name(dt, locale='en_US') ==
                u'Pacific Standard Time')
        assert (dates.get_timezone_name(dt, locale='en_US', return_zone=True) ==
                u'America/Los_Angeles')
        assert dates.get_timezone_name(dt, width='short', locale='en_US') == u'PST'

        tz = timezone('America/Los_Angeles')
        assert dates.get_timezone_name(tz, locale='en_US') == u'Pacific Time'
        assert dates.get_timezone_name(tz, 'short', locale='en_US') == u'PT'

        tz = timezone('Europe/Berlin')
        assert (dates.get_timezone_name(tz, locale='de_DE') ==
                u'Mitteleurop\xe4ische Zeit')
        assert (dates.get_timezone_name(tz, locale='pt_BR') ==
                u'Hor\xe1rio da Europa Central')

        tz = timezone('America/St_Johns')
        assert dates.get_timezone_name(tz, locale='de_DE') == u'Neufundland-Zeit'

        tz = timezone('America/Los_Angeles')
        assert dates.get_timezone_name(tz, locale='en', width='short',
                                       zone_variant='generic') == u'PT'
        assert dates.get_timezone_name(tz, locale='en', width='short',
                                       zone_variant='standard') == u'PST'
        assert dates.get_timezone_name(tz, locale='en', width='short',
                                       zone_variant='daylight') == u'PDT'
        assert dates.get_timezone_name(tz, locale='en', width='long',
                                       zone_variant='generic') == u'Pacific Time'
        assert dates.get_timezone_name(tz, locale='en', width='long',
                                       zone_variant='standard') == u'Pacific Standard Time'
        assert dates.get_timezone_name(tz, locale='en', width='long',
                                       zone_variant='daylight') == u'Pacific Daylight Time'

        localnow = datetime.utcnow().replace(tzinfo=timezone('UTC')).astimezone(dates.LOCALTZ)
>       assert (dates.get_timezone_name(None, locale='en_US') ==
                dates.get_timezone_name(localnow, locale='en_US'))
E       assert 'GMT+00:00' == 'GMT+07:00'
E         - GMT+00:00
E         ?      ^
E         + GMT+07:00
E         ?      ^

tests/test_dates.py:628: AssertionError
====================================== pytest-warning summary ======================================
WC1 None [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.
====================== 1 failed, 67 passed, 1 pytest-warnings in 0.31 seconds =================
```
# Additional Information

Tested with git master (5c02138363a0c0e1fbbfeccf2c6f5f731b6dee92), pytz==2016.6.1.

**Comment by warsaw** [comment] 2017-04-05 18:41
I wonder if this is related to the failure I'm seeing in local build tests of the Debian package of 2.3.4+dfsg.1-2:

```
____________________________ test_get_timezone_name ____________________________

    def test_get_timezone_name():
        dt = time(15, 30, tzinfo=timezone('America/Los_Angeles'))
        assert (dates.get_timezone_name(dt, locale='en_US') ==
                u'Pacific Standard Time')
        assert (dates.get_timezone_name(dt, locale='en_US', return_zone=True) ==
                u'America/Los_Angeles')
        assert dates.get_timezone_name(dt, width='short', locale='en_US') == u'PST'
    
        tz = timezone('America/Los_Angeles')
        assert dates.get_timezone_name(tz, locale='en_US') == u'Pacific Time'
        assert dates.get_timezone_name(tz, 'short', locale='en_US') == u'PT'
    
        tz = timezone('Europe/Berlin')
        assert (dates.get_timezone_name(tz, locale='de_DE') ==
                u'Mitteleurop\xe4ische Zeit')
        assert (dates.get_timezone_name(tz, locale='pt_BR') ==
                u'Hor\xe1rio da Europa Central')
    
        tz = timezone('America/St_Johns')
        assert dates.get_timezone_name(tz, locale='de_DE') == u'Neufundland-Zeit'
    
        tz = timezone('America/Los_Angeles')
        assert dates.get_timezone_name(tz, locale='en', width='short',
                                       zone_variant='generic') == u'PT'
        assert dates.get_timezone_name(tz, locale='en', width='short',
                                       zone_variant='standard') == u'PST'
        assert dates.get_timezone_name(tz, locale='en', width='short',
                                       zone_variant='daylight') == u'PDT'
        assert dates.get_timezone_name(tz, locale='en', width='long',
                                       zone_variant='generic') == u'Pacific Time'
        assert dates.get_timezone_name(tz, locale='en', width='long',
                                       zone_variant='standard') == u'Pacific Standard Time'
        assert dates.get_timezone_name(tz, locale='en', width='long',
                                       zone_variant='daylight') == u'Pacific Daylight Time'
    
>       assert (dates.get_timezone_name(None, locale='en_US') ==
                dates.get_timezone_name(datetime.now().replace(tzinfo=dates.LOCALTZ), locale='en_US'))
E       assert 'Eastern Daylight Time' == 'Eastern Standard Time'
E         - Eastern Daylight Time
E         + Eastern Standard Time

```

**Comment by warsaw** [comment] 2017-04-05 18:44
Or maybe it's #370

**Comment by akx** [comment] 2017-04-05 18:50
Yup. This is fixed in 2.4.0 though (via #411).

**Comment by warsaw** [comment] 2017-04-05 19:02
@akx Thanks, and confirmed it does fix things for us in Ubuntu.  We can't update to 2.4.0 because we're in beta freeze (and Debian is in freeze too), so I'll just cherry pick the patch.

**Comment by akx** [comment] 2017-04-05 19:52
@warsaw Okay, great! Closing this issue, but obviously do let us know if there's anything we can do to make things easier for you folks :)

**Closed by akx** 2017-04-05 19:52 UTC
