### ISSUE TITLE
Any plan to load the latest version of CLDR? 

### ISSUE THREAD

**Issue by hanteng** [python-babel/babel#99] opened 2014-05-29 05:48 UTC
Any plan to load the latest version of CLDR? I have tried to modified the code to load the CLDR 25, with only some limited success. Pluralization rules appear to need more work to digest the CLDR 25.

**Comment by benselme** [comment] 2015-01-09 20:54
See #135 for preliminary cldr-24 support.

**Comment by srl295** [comment] 2015-01-09 22:27
@benselme It's a good improvement,  CLDR 26 was released in August, 2014 for what it's worth. Please make use of resources such as the [cldr-users](http://www.unicode.org/consortium/distlist-cldr-users.html) list and the bug tracker on http://cldr.unicode.org/

**Comment by benselme** [comment] 2015-01-09 22:57
My plan is to incrementally get to the latest version.

**Comment by srl295** [comment] 2015-01-10 01:06
@benselme makes sense.

**Comment by sils1297** [comment] 2015-09-21 16:00
Hi, closing this one as a duplicate of https://github.com/python-babel/babel/issues/226 . I'd love to see a PR solving that one, be it incrementally or not.

**Closed by sils1297** 2015-09-21 16:00 UTC
