### ISSUE TITLE
French dates should use "19h01" instead of "19:01"

### ISSUE THREAD

**Issue by tewalds** [python-babel/babel#150] opened 2015-03-16 16:10 UTC
The proper french way to show a time is "19h01" instead of "19:01" as it is now.

**Comment by benselme** [comment] 2015-03-16 20:31
Both "19:01" and "19h01" are acceptablem but  in different contexts. The former is recommended when displaying a time table for example.

The `format_time` function accepts a `format` parameter the default value of which is `'medium'`. You should get the format you want if you pass `format='full'`.

**Comment by tewalds** [comment] 2015-03-16 22:31
That doesn't seem to do it for me either:

n = datetime.datetime(2015, 3, 13, 16, 49, 9, 358524).replace(tzinfo=dates.get_timezone('Europe/Paris')) 

dates.format_datetime(n, 'short', locale='fr') => '13/03/2015 16:49'
dates.format_datetime(n, 'medium', locale='fr') => '13 mars 2015 16:49:09'
dates.format_datetime(n, 'long', locale='fr') => '13 mars 2015 16:49:09 +0009'
dates.format_datetime(n, 'full', locale='fr') => 'vendredi 13 mars 2015 16:49:09 heure normale de l\u2019Europe centrale'

**Comment by remyroy** [comment] 2015-04-02 01:40
In the latest [CLDR release](http://cldr.unicode.org/index/downloads) (27.0.1), the various format patterns for displaying time use ":" as the hour and minutes separator. This is the case for the generic fr locale but also for the more specific fr_FR and fr_CA.

As a French Canadian, I have been used to using "h" as the hour and minutes separator which seems a little odd to me.

I've also checked in the Windows 7 regional settings and it seems like ":" is the separator for both French (France) and French (Canada). If my memory is correct, in a previous Windows, "h" was actually the separator which is why I looked there but Windows might have changed to use CLDR data now.

My conclusion on this is that I'm confused ! CLDR and most importantly the Unicode body is supposed to be a standard and they should have some pretty good references and experts to do what they do. There might have been a French institution somewhere that enacted this change without this making the news on which the Unicode body relies to make their own data.

**Comment by remyroy** [comment] 2015-04-02 01:46
Just for fun, I went looking at pass releases of CLDR. I've checked version 1.1.1 which was released in 2004 and it seems like *that version* had format patterns that used "h" as the hours and minutes separator.

So this changed in the last 11 years.

I hate to say this but according to Unicode, ":" is the hours and minutes separator for French. This is not a bug and can be closed.

**Comment by remyroy** [comment] 2015-04-02 04:24
If you truly believe "h" should be the separator for time patterns, I would invite you to join the Unicode body and take part in their effort to provide the best information possible. You can file a ticket for the Unicode CLDR here: http://cldr.unicode.org/index/bug-reports . You will have to provide good references in order to convince them.

Alternatively, you could use a custom format pattern.

**Comment by etanol** [comment] 2015-09-26 09:38
@remyroy thanks for digging deeper.  This, therefore, seems like a CLDR related issue. Closing

**Closed by etanol** 2015-09-26 09:38 UTC
Labels: invalid

**Comment by sils1297** [comment] 2015-09-26 12:26
Could someone file a bug upstream for this/did someone? Otherwise I actually wouldn't consider this issue resolved for us.

**Comment by sils1297** [comment] 2015-09-26 18:11
Filed upstream as http://unicode.org/cldr/trac/ticket/8999

**Comment by benselme** [comment] 2015-10-01 23:40
Just for reference, this was discussed on the cldr mailing-list not very long ago:
http://unicode.org/pipermail/cldr-users/2015-May/thread.html#295
