### ISSUE TITLE
Wrong year in format_date for date in first week of year

### ISSUE THREAD

**Issue by pavel-francirek** [python-babel/babel#419] opened 2016-06-17 18:00 UTC
How to duplicate:

```
$ python
Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import date, datetime, time
>>> from babel.dates import format_date, format_datetime, format_time
>>> d = date(2016, 1, 2)
>>> format_date(d, format= 'd. MMMM YYYY',locale='en')
u'2. January 2016'
>>> format_date(d, format= 'd. MMMM YYYY',locale='de_DE')
u'2. Januar 2015'
>>> 
```

Package python-flask-babel 0.9-2.1 in Ubuntu 16.04 (older version are affected too)

**Comment by jun66j5** [comment] 2016-06-17 19:16
Not a bug. Try `yyyy` (lower case) instead of `YYYY`.

According to http://babel.pocoo.org/en/latest/dates.html#date-fields:

 - `y`: Replaced by the year. Normally the length specifies the padding, but for two letters it also specifies the maximum length.
 - `Y`: Same as y but uses the ISO year-week calendar.

```
>>> import babel
>>> from babel.dates import format_date
>>> from datetime import datetime
>>> babel.__version__
'2.2.0'
>>> t = datetime(2016, 1, 2)
>>> format_date(t, 'd. MMMM yyyy', locale='en_US')
u'2. January 2016'
>>> format_date(t, 'd. MMMM yyyy', locale='de_DE')
u'2. Januar 2016'
>>> format_date(t, 'YYYY-ww', locale='en_US')
u'2016-01'
>>> format_date(t, 'YYYY-ww', locale='de_DE')
u'2015-53'
```

**Comment by akx** [comment] 2016-06-17 19:27
@jun66j5 Cheers for the triaging. I think this could use clarification (with an example -- perhaps exactly the example you have above) in the docs though :)

**Comment by pavel-francirek** [comment] 2016-06-17 20:28
Oh, I see. Thank you. But I agree that it should be mentioned in documentation. Especially if there is no clear connection between year and week number.

**Comment by ldwoolley** [comment] 2016-10-07 23:25
Per the example jun66j5, the "w" symbol description should also indicate that it follows ISO week standard, which may have 52 or 53 weeks depending on the year. Perhaps "Y" and "w" should reference each other in the document.  I will submit a proposal.  Also, it seems unfortunate that the ISO year-week year is capital while the week is not.

**Comment by akx** [comment] 2016-11-21 14:52
The documentation was improved by @ldwoolley in #450, so closing. Thanks :)

**Closed by akx** 2016-11-21 14:52 UTC
Labels: difficulty/low, documentation
