### ISSUE TITLE
`global.dat` cannot be unpickled with Python 3.5

### ISSUE THREAD

**Issue by abakan** [python-babel/babel#221] opened 2015-09-16 00:44 UTC
`global.dat` cannot be unpickled with Python 3.5. This causes a problem when installing packages that use Babel's `message_extractors` with `pip`.

```python
Python 3.5.0 (default, Sep 14 2015, 02:37:27)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> pickle.load(open('/usr/local/lib/python3.5/site-packages/babel/global.dat', 'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: an integer is required (got type str)
```
Exception is thrown in `core.py`: https://github.com/mitsuhiko/babel/blob/master/babel/core.py#L56

**Comment by gschizas** [comment] 2015-09-16 14:08
This is probably a duplicate of this: https://github.com/mitsuhiko/babel/issues/174

(TL;DR do a ```pip install --upgrade git+https://github.com/mitsuhiko/babel.git@2.0```)

**Closed** 2016-01-15 14:55 UTC
Labels: status/needs info
